/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OdeLibrary {

using System;
using System.Runtime.InteropServices;

public class ComplexOde : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ComplexOde(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ComplexOde obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ComplexOde() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_ComplexOde(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ComplexStateType InitialConditions {
    set {
      CorePINVOKE.ComplexOde_InitialConditions_set(swigCPtr, ComplexStateType.getCPtr(value));
    } 
    get {
      IntPtr cPtr = CorePINVOKE.ComplexOde_InitialConditions_get(swigCPtr);
      ComplexStateType ret = (cPtr == IntPtr.Zero) ? null : new ComplexStateType(cPtr, false);
      return ret;
    } 
  }

    protected virtual void system(ComplexStateType x, ComplexStateType dxdt, double t) {
    if (SwigDerivedClassHasMethod("system", swigMethodTypes0)) CorePINVOKE.ComplexOde_systemSwigExplicitComplexOde(swigCPtr, ComplexStateType.getCPtr(x), ComplexStateType.getCPtr(dxdt), t); else CorePINVOKE.ComplexOde_system(swigCPtr, ComplexStateType.getCPtr(x), ComplexStateType.getCPtr(dxdt), t);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

    protected virtual void observer(ComplexStateType x, double t) {
    if (SwigDerivedClassHasMethod("observer", swigMethodTypes1)) CorePINVOKE.ComplexOde_observerSwigExplicitComplexOde(swigCPtr, ComplexStateType.getCPtr(x), t); else CorePINVOKE.ComplexOde_observer(swigCPtr, ComplexStateType.getCPtr(x), t);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public ComplexOde() : this(CorePINVOKE.new_ComplexOde(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("system", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateComplexOde_0(SwigDirectorsystem);
    if (SwigDerivedClassHasMethod("observer", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateComplexOde_1(SwigDirectorobserver);
    CorePINVOKE.ComplexOde_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ComplexOde));
    return hasDerivedMethod;
  }

  private void SwigDirectorsystem(IntPtr x, IntPtr dxdt, double t) {
    system(new ComplexStateType(x, false), new ComplexStateType(dxdt, false), t);
  }

  private void SwigDirectorobserver(IntPtr x, double t) {
    observer(new ComplexStateType(x, false), t);
  }

  public delegate void SwigDelegateComplexOde_0(IntPtr x, IntPtr dxdt, double t);
  public delegate void SwigDelegateComplexOde_1(IntPtr x, double t);

  private SwigDelegateComplexOde_0 swigDelegate0;
  private SwigDelegateComplexOde_1 swigDelegate1;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(ComplexStateType), typeof(ComplexStateType), typeof(double) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(ComplexStateType), typeof(double) };
}

}
