/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OdeLibrary {

using System;
using System.Runtime.InteropServices;

class CorePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("Core", EntryPoint="SWIGRegisterExceptionCallbacks_Core")]
    public static extern void SWIGRegisterExceptionCallbacks_Core(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("Core", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_Core")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_Core(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_Core(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_Core(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(CorePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(CorePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("Core", EntryPoint="SWIGRegisterStringCallback_Core")]
    public static extern void SWIGRegisterStringCallback_Core(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_Core(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static CorePINVOKE() {
  }


  [DllImport("Core", EntryPoint="CSharp_new_Complex__SWIG_0")]
  public static extern IntPtr new_Complex__SWIG_0(double jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_new_Complex__SWIG_1")]
  public static extern IntPtr new_Complex__SWIG_1(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Complex_imag")]
  public static extern double Complex_imag(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Complex_real")]
  public static extern double Complex_real(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Complex_Multiply__SWIG_0")]
  public static extern IntPtr Complex_Multiply__SWIG_0(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_Complex_Add")]
  public static extern IntPtr Complex_Add(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_Complex_Substract")]
  public static extern IntPtr Complex_Substract(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_Complex_Multiply__SWIG_1")]
  public static extern IntPtr Complex_Multiply__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_Complex_Divide")]
  public static extern IntPtr Complex_Divide(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_delete_Complex")]
  public static extern void delete_Complex(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_Clear")]
  public static extern void StateType_Clear(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_Add")]
  public static extern void StateType_Add(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_size")]
  public static extern uint StateType_size(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_capacity")]
  public static extern uint StateType_capacity(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_reserve")]
  public static extern void StateType_reserve(HandleRef jarg1, uint jarg2);

  [DllImport("Core", EntryPoint="CSharp_new_StateType__SWIG_0")]
  public static extern IntPtr new_StateType__SWIG_0();

  [DllImport("Core", EntryPoint="CSharp_new_StateType__SWIG_1")]
  public static extern IntPtr new_StateType__SWIG_1(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_new_StateType__SWIG_2")]
  public static extern IntPtr new_StateType__SWIG_2(int jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_getitemcopy")]
  public static extern double StateType_getitemcopy(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_getitem")]
  public static extern double StateType_getitem(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_setitem")]
  public static extern void StateType_setitem(HandleRef jarg1, int jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_AddRange")]
  public static extern void StateType_AddRange(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_GetRange")]
  public static extern IntPtr StateType_GetRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_Insert")]
  public static extern void StateType_Insert(HandleRef jarg1, int jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_InsertRange")]
  public static extern void StateType_InsertRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_RemoveAt")]
  public static extern void StateType_RemoveAt(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_RemoveRange")]
  public static extern void StateType_RemoveRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_Repeat")]
  public static extern IntPtr StateType_Repeat(double jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_Reverse__SWIG_0")]
  public static extern void StateType_Reverse__SWIG_0(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_StateType_Reverse__SWIG_1")]
  public static extern void StateType_Reverse__SWIG_1(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_SetRange")]
  public static extern void StateType_SetRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_StateType_Contains")]
  public static extern bool StateType_Contains(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_IndexOf")]
  public static extern int StateType_IndexOf(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_LastIndexOf")]
  public static extern int StateType_LastIndexOf(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_StateType_Remove")]
  public static extern bool StateType_Remove(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_delete_StateType")]
  public static extern void delete_StateType(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_InitialConditions_set")]
  public static extern void Ode_InitialConditions_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_Ode_InitialConditions_get")]
  public static extern IntPtr Ode_InitialConditions_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_delete_Ode")]
  public static extern void delete_Ode(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_system")]
  public static extern void Ode_system(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_Ode_systemSwigExplicitOde")]
  public static extern void Ode_systemSwigExplicitOde(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_Ode_observer")]
  public static extern void Ode_observer(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_Ode_observerSwigExplicitOde")]
  public static extern void Ode_observerSwigExplicitOde(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_new_Ode")]
  public static extern IntPtr new_Ode();

  [DllImport("Core", EntryPoint="CSharp_Ode_director_connect")]
  public static extern void Ode_director_connect(HandleRef jarg1, Ode.SwigDelegateOde_0 delegate0, Ode.SwigDelegateOde_1 delegate1);

  [DllImport("Core", EntryPoint="CSharp_Solver_StepperCode_set")]
  public static extern void Solver_StepperCode_set(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_Solver_StepperCode_get")]
  public static extern int Solver_StepperCode_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Solver_ConvenienceSolve")]
  public static extern int Solver_ConvenienceSolve(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5);

  [DllImport("Core", EntryPoint="CSharp_Solver_Solve__SWIG_0")]
  public static extern int Solver_Solve__SWIG_0(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5, int jarg6);

  [DllImport("Core", EntryPoint="CSharp_Solver_Solve__SWIG_1")]
  public static extern int Solver_Solve__SWIG_1(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5);

  [DllImport("Core", EntryPoint="CSharp_Solver_Solve__SWIG_2")]
  public static extern int Solver_Solve__SWIG_2(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, int jarg5);

  [DllImport("Core", EntryPoint="CSharp_Solver_Solve__SWIG_3")]
  public static extern int Solver_Solve__SWIG_3(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_new_Solver")]
  public static extern IntPtr new_Solver();

  [DllImport("Core", EntryPoint="CSharp_delete_Solver")]
  public static extern void delete_Solver(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Clear")]
  public static extern void ComplexStateType_Clear(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Add")]
  public static extern void ComplexStateType_Add(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_size")]
  public static extern uint ComplexStateType_size(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_capacity")]
  public static extern uint ComplexStateType_capacity(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_reserve")]
  public static extern void ComplexStateType_reserve(HandleRef jarg1, uint jarg2);

  [DllImport("Core", EntryPoint="CSharp_new_ComplexStateType__SWIG_0")]
  public static extern IntPtr new_ComplexStateType__SWIG_0();

  [DllImport("Core", EntryPoint="CSharp_new_ComplexStateType__SWIG_1")]
  public static extern IntPtr new_ComplexStateType__SWIG_1(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_new_ComplexStateType__SWIG_2")]
  public static extern IntPtr new_ComplexStateType__SWIG_2(int jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_getitemcopy")]
  public static extern IntPtr ComplexStateType_getitemcopy(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_getitem")]
  public static extern IntPtr ComplexStateType_getitem(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_setitem")]
  public static extern void ComplexStateType_setitem(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_AddRange")]
  public static extern void ComplexStateType_AddRange(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_GetRange")]
  public static extern IntPtr ComplexStateType_GetRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Insert")]
  public static extern void ComplexStateType_Insert(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_InsertRange")]
  public static extern void ComplexStateType_InsertRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_RemoveAt")]
  public static extern void ComplexStateType_RemoveAt(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_RemoveRange")]
  public static extern void ComplexStateType_RemoveRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Repeat")]
  public static extern IntPtr ComplexStateType_Repeat(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Reverse__SWIG_0")]
  public static extern void ComplexStateType_Reverse__SWIG_0(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_Reverse__SWIG_1")]
  public static extern void ComplexStateType_Reverse__SWIG_1(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexStateType_SetRange")]
  public static extern void ComplexStateType_SetRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_delete_ComplexStateType")]
  public static extern void delete_ComplexStateType(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_InitialConditions_set")]
  public static extern void ComplexOde_InitialConditions_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_InitialConditions_get")]
  public static extern IntPtr ComplexOde_InitialConditions_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_delete_ComplexOde")]
  public static extern void delete_ComplexOde(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_system")]
  public static extern void ComplexOde_system(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_systemSwigExplicitComplexOde")]
  public static extern void ComplexOde_systemSwigExplicitComplexOde(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_observer")]
  public static extern void ComplexOde_observer(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_observerSwigExplicitComplexOde")]
  public static extern void ComplexOde_observerSwigExplicitComplexOde(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_new_ComplexOde")]
  public static extern IntPtr new_ComplexOde();

  [DllImport("Core", EntryPoint="CSharp_ComplexOde_director_connect")]
  public static extern void ComplexOde_director_connect(HandleRef jarg1, ComplexOde.SwigDelegateComplexOde_0 delegate0, ComplexOde.SwigDelegateComplexOde_1 delegate1);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_StepperCode_set")]
  public static extern void ComplexSolver_StepperCode_set(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_StepperCode_get")]
  public static extern int ComplexSolver_StepperCode_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_ConvenienceSolve")]
  public static extern int ComplexSolver_ConvenienceSolve(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_Solve__SWIG_0")]
  public static extern int ComplexSolver_Solve__SWIG_0(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5, int jarg6);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_Solve__SWIG_1")]
  public static extern int ComplexSolver_Solve__SWIG_1(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, double jarg5);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_Solve__SWIG_2")]
  public static extern int ComplexSolver_Solve__SWIG_2(HandleRef jarg1, HandleRef jarg2, double jarg3, double jarg4, int jarg5);

  [DllImport("Core", EntryPoint="CSharp_ComplexSolver_Solve__SWIG_3")]
  public static extern int ComplexSolver_Solve__SWIG_3(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_new_ComplexSolver")]
  public static extern IntPtr new_ComplexSolver();

  [DllImport("Core", EntryPoint="CSharp_delete_ComplexSolver")]
  public static extern void delete_ComplexSolver(HandleRef jarg1);
}

}
