/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OdeLibrary
{

    public enum Stepper
    {
        Default,
        Euler, // Works only with IntegrateFunction.NSteps
        ModifiedMidpoint,
        RungeKutta4,
        RungeKuttaCashKarp54,
        RungeKuttaDopri5,
        RungeKuttaFehlberg78,
        ControlledRungeKutta,
        BulirschStoer,
        BulirschStoerDenseOut,
    }

}
