/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OdeLibrary {

using System;
using System.Runtime.InteropServices;

class CorePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("Core", EntryPoint="SWIGRegisterExceptionCallbacks_Core")]
    public static extern void SWIGRegisterExceptionCallbacks_Core(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("Core", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_Core")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_Core(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_Core(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_Core(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(CorePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(CorePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("Core", EntryPoint="SWIGRegisterStringCallback_Core")]
    public static extern void SWIGRegisterStringCallback_Core(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_Core(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static CorePINVOKE() {
  }


  [DllImport("Core", EntryPoint="CSharp_state_type_Clear")]
  public static extern void state_type_Clear(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_state_type_Add")]
  public static extern void state_type_Add(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_size")]
  public static extern uint state_type_size(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_state_type_capacity")]
  public static extern uint state_type_capacity(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_state_type_reserve")]
  public static extern void state_type_reserve(HandleRef jarg1, uint jarg2);

  [DllImport("Core", EntryPoint="CSharp_new_state_type__SWIG_0")]
  public static extern IntPtr new_state_type__SWIG_0();

  [DllImport("Core", EntryPoint="CSharp_new_state_type__SWIG_1")]
  public static extern IntPtr new_state_type__SWIG_1(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_new_state_type__SWIG_2")]
  public static extern IntPtr new_state_type__SWIG_2(int jarg1);

  [DllImport("Core", EntryPoint="CSharp_state_type_getitemcopy")]
  public static extern double state_type_getitemcopy(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_getitem")]
  public static extern double state_type_getitem(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_setitem")]
  public static extern void state_type_setitem(HandleRef jarg1, int jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_AddRange")]
  public static extern void state_type_AddRange(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_GetRange")]
  public static extern IntPtr state_type_GetRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_Insert")]
  public static extern void state_type_Insert(HandleRef jarg1, int jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_InsertRange")]
  public static extern void state_type_InsertRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_RemoveAt")]
  public static extern void state_type_RemoveAt(HandleRef jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_RemoveRange")]
  public static extern void state_type_RemoveRange(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_Repeat")]
  public static extern IntPtr state_type_Repeat(double jarg1, int jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_Reverse__SWIG_0")]
  public static extern void state_type_Reverse__SWIG_0(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_state_type_Reverse__SWIG_1")]
  public static extern void state_type_Reverse__SWIG_1(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_SetRange")]
  public static extern void state_type_SetRange(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("Core", EntryPoint="CSharp_state_type_Contains")]
  public static extern bool state_type_Contains(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_IndexOf")]
  public static extern int state_type_IndexOf(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_LastIndexOf")]
  public static extern int state_type_LastIndexOf(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_state_type_Remove")]
  public static extern bool state_type_Remove(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_delete_state_type")]
  public static extern void delete_state_type(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_system")]
  public static extern void Ode_system(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_Ode_systemSwigExplicitOde")]
  public static extern void Ode_systemSwigExplicitOde(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, double jarg4);

  [DllImport("Core", EntryPoint="CSharp_Ode_observer")]
  public static extern void Ode_observer(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_Ode_observerSwigExplicitOde")]
  public static extern void Ode_observerSwigExplicitOde(HandleRef jarg1, HandleRef jarg2, double jarg3);

  [DllImport("Core", EntryPoint="CSharp_Ode_initialConditions_set")]
  public static extern void Ode_initialConditions_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_Ode_initialConditions_get")]
  public static extern IntPtr Ode_initialConditions_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_from_set")]
  public static extern void Ode_from_set(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_Ode_from_get")]
  public static extern double Ode_from_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_to_set")]
  public static extern void Ode_to_set(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_Ode_to_get")]
  public static extern double Ode_to_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_Ode_step_set")]
  public static extern void Ode_step_set(HandleRef jarg1, double jarg2);

  [DllImport("Core", EntryPoint="CSharp_Ode_step_get")]
  public static extern double Ode_step_get(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_delete_Ode")]
  public static extern void delete_Ode(HandleRef jarg1);

  [DllImport("Core", EntryPoint="CSharp_new_Ode")]
  public static extern IntPtr new_Ode();

  [DllImport("Core", EntryPoint="CSharp_Ode_director_connect")]
  public static extern void Ode_director_connect(HandleRef jarg1, Ode.SwigDelegateOde_0 delegate0, Ode.SwigDelegateOde_1 delegate1);

  [DllImport("Core", EntryPoint="CSharp_Solver_Solve")]
  public static extern int Solver_Solve(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Core", EntryPoint="CSharp_new_Solver")]
  public static extern IntPtr new_Solver();

  [DllImport("Core", EntryPoint="CSharp_delete_Solver")]
  public static extern void delete_Solver(HandleRef jarg1);
}

}
