/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Core_WRAP_H_
#define SWIG_Core_WRAP_H_

class SwigDirector_Ode : public OdeProxy::Ode, public Swig::Director {

public:
    SwigDirector_Ode();
    virtual void system(OdeProxy::StateType const &x, OdeProxy::StateType &dxdt, double t);
    virtual void observer(OdeProxy::StateType const &x, double t);
    virtual ~SwigDirector_Ode();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *, double);
    void swig_connect_director(SWIG_Callback0_t callbacksystem, SWIG_Callback1_t callbackobserver);

private:
    SWIG_Callback0_t swig_callbacksystem;
    SWIG_Callback1_t swig_callbackobserver;
    void swig_init_callbacks();
};


#endif
